draft_journal_entry.txt:prueba
programa make
no tengo el archivo base
construyendo un directorio
no se qIn the simple example we created draft_journal_entry.txt is the target,
 a file which is created as the result of the command(s). It’s very important to note that any commands under a target must be indented with a Tab.
 If we don’t use Tabs to indent the commands then make will fail.
 Let’s save and close the makefile, then we can run the foll
owing in the console:^

